### PR TITLE
Switch to using Ansible for node registration

### PR DESCRIPTION
**Pull request by antonym**
The existing method appeared to be buggy and not register
nodes.  Switching to using the other recommended way of
registering nodes using Ansible.

### CODE REVIEW

**Comment by tonytan4ever** [comment]
recheck_xenial_mnaio_3ctlr_2comp_3ceph_osp_13_deploy

**Comment by antonym** [comment]
recheck_all

**Comment by antonym** [comment]
This appears to be working, and the Ansible code is properly adding the repos to the overcloud nodes after overcloud install.

I'll be making one more change, flipping the flag to false as I had flipped it to true to test so that this doesn't over register things when running CI.

**Comment by antonym** [comment]
Merging as this has already passed and I'm turning off the flag so it no longer fires during CI testing.

**Pull request merged**
