### PR TITLE
Generate template structure from directory

### PR DESCRIPTION
**Pull request by antonym**
Generates templates residing in osp/version
and adds them to director node.

Allows for variation in templates across versions
without a lot of specific code for each version.

### CODE REVIEW

**Comment by coreywright** [comment]
so if i understand this PR correctly... you are refactoring the `playbooks/osp/${VERSION}` subdirectories so that the contents of those directories can be recreated on the director without them being referenced specifically in the playbook (presumably in preparation for you adding the necessary files for RH OSP 10 which deviate by filename and/or file count from 12 & 13 and wanting to avoid adding conditionals to the playbook).

my only concern is as all the files are treated as templates, there might be files that aren't templates  but that contain `{{ ... }}` which get expanded needlessly and destructively change the file, but i don't see anything like that currently so my concern is currently unfounded.

LGTM (assuming neither you nor i overlooked something that testing catches).

**Comment by antonym** [comment]
Yeah, I guess if we run into probs, I can always make the structure a bit deeper into files and templates and then just shift files around that way.  But yeah, since each release can potentially have different files and I want to be able to handle more versions, it seems easier just to generate the structure this way.  I did a quick test to see if it would work and it appeared to generate things properly so just letting the gating stress it now.

**Comment by antonym** [comment]
recheck_all

**Comment by antonym** [comment]
recheck_xenial_mnaio_3ctlr_2comp_3ceph_osp_13_deploy

**Comment by antonym** [comment]
Deploy and tests are passing, merging this in.  If you see any issues that pop up from this, let me know.

**Pull request merged**
