### PR TITLE
RI-463 Add Tempest testing

### PR DESCRIPTION
**Pull request by coreywright**
* RI-463 Add Tempest testing
* RI-463 Collect OpenStack service logs as artifacts
* gating: Refactor env vars into separate file
* Create and copy from director log files with .log extension

Issue: https://rpc-openstack.atlassian.net/browse/RI-463

### CODE REVIEW

**Comment by coreywright** [comment]
let's see if the test deployment fails, and if so, then if it is because of nested virtualization not being enabled, ie `libvirtError: invalid argument: could not find capabilities for domaintype=kvm` (see https://gist.github.com/coreywright/373b82d9d9ee5ced6c858f63f68e89fe).

**Comment by coreywright** [comment]
so, tempest integration tests pass (well, just the 2 basic ops scenarios we run), but without nested virtualization being explicitly enabled (by us), which is not my experience testing in another environment with a different base image on a different version of ubuntu, so i've added a commit with the sole purpose of inspecting the Jenkins build slave to figure out whether nested virtualization is enabled (eg before & after test).

**Comment by coreywright** [comment]
remove "inspect jenkins build slave for nested virt" commit and restart deployment test now that ceph commit is merged (which i expect to cause tests to fail based on previous experience with ceph and tempest using tripleo-quickstart, ie https://access.redhat.com/solutions/2858981 and `object-storage-feature-enabled.discoverability false`).

**Comment by antonym** [comment]
The default install includes Swift as an object store so I'm wondering if installing ceph and RadosGW overrides that.  I don't think I added any options to explicitly change the store so I'm under the assumption it would still use Swift for that.  Also that KB references Ceph 2 and we should be using 3. (not sure if it still applies still or not)

**Comment by coreywright** [comment]
@antonym,

you added `-e /usr/share/openstack-tripleo-heat-templates/environments/ceph-ansible/ceph-rgw.yaml`, which is essentially all i did for tripleo-quickstart which enabled radosgw and caused the 404 failure calling the /info endpoint on the swift (now radosgw) api.  that's why i expect the same test failure, but i'll see soon enough.

interestingly i didn't see you also add `-e /usr/share/openstack-tripleo-heat-templates/environments/ceph-ansible/ceph-mds.yaml` which i added in tripleo-quickstart as part of my ceph enablement, though i can't remember what ceph mds is (and therefor the importance of it, if any).

**Comment by antonym** [comment]
Ok, so simply adding the ceph-rgw.yaml is the trigger then to flip the usage of it, got it.  Yeah, I left out mds because the guide mentioned that it was in tech preview and unsupported, so I figured it's not something we'd deploy by default.

**Comment by coreywright** [comment]
interestingly the build failure that occurred in jenkins is the same as the one that occurred on my dev node, and my dev node was commit eae1e05 / branch add_ceph_support where i was trying to personally test and review the ceph PR, where here it's that and my tempest commits:
```
2018-09-19 18:37:37Z [overcloud.AllNodesDeploySteps.WorkflowTasks_Step2_Execution]: CREATE_FAILED  resources.WorkflowTasks_Step2_Execution: ERROR
2018-09-19 18:37:37Z [overcloud.AllNodesDeploySteps]: CREATE_FAILED  Resource CREATE failed: resources.WorkflowTasks_Step2_Execution: ERROR
2018-09-19 18:37:38Z [overcloud.AllNodesDeploySteps]: CREATE_FAILED  resources.AllNodesDeploySteps: Resource CREATE failed: resources.WorkflowTasks_Step2_Execution: ERROR
2018-09-19 18:37:38Z [overcloud]: CREATE_FAILED  Resource CREATE failed: resources.AllNodesDeploySteps: Resource CREATE failed: resources.WorkflowTasks_Step2_Execution: ERROR

 Stack overcloud CREATE_FAILED 

overcloud.AllNodesDeploySteps.WorkflowTasks_Step2_Execution:
  resource_type: OS::TripleO::WorkflowSteps
  physical_resource_id: 2d6a9bb3-ba40-47d7-bf26-61922c574141
  status: CREATE_FAILED
  status_reason: |
    resources.WorkflowTasks_Step2_Execution: ERROR
```
that's the tail of my director/overcloud_install.log for comparison to the one captured by jenkins (which, again appears identical to me except for UUIDs).

**Comment by antonym** [comment]
That was the error I was getting before tuning some of the ceph settings, I wonder if it just needs a rebase?

**Comment by coreywright** [comment]
@antonym,

`"msg": "'dict object' has no attribute 'rgw_hostname'"` during `TASK [ceph-config : generate ceph.conf configuration file]` on overcloud-controller-1/192.168.24.19.

see https://gist.github.com/coreywright/7ae36224345f2bf5e77e93c8f778f28e

**Comment by antonym** [comment]
Heh, looks like some talk on this one recently:

https://bugzilla.redhat.com/show_bug.cgi?id=1622505
https://bugzilla.redhat.com/show_bug.cgi?id=1618678

Should I just pull out rgw for now?

**Comment by antonym** [comment]
recheck_xenial_mnaio_3ctlr_2comp_3ceph_osp_13_deploy

**Comment by antonym** [comment]
recheck_xenial_mnaio_3ctlr_2comp_3ceph_osp_13_deploy

looks like deploy works now but fails during test because a previous commit dumps the overcloudrc elsewhere, rechecking with https://github.com/rcbops/osp-mnaio/pull/26 to ensure the overcloudrc stays in /home/stack.

**Comment by coreywright** [comment]
fresh deployment to my dev node and ran all tempest smoke tests (not just the two scenario-based smoke tests we do in the PR gate) to get more assurance that everything is working after all the recent changes.

```
[stack@director ~]$ TEMPEST_TESTS='--smoke' scripts/overcloud-test.sh
...
# Run Tempest tests.
tempest run ${TEMPEST_OPTIONS} ${TEMPEST_TESTS} || RC=${?}
+ tempest run --concurrency 1 --smoke
...
======
Totals
======
Ran: 107 tests in 1680.0000 sec.
 - Passed: 103
 - Skipped: 4
 - Expected Fail: 0
 - Unexpected Success: 0
 - Failed: 0
Sum of execute time for each test: 701.3706 sec.
```

**Comment by antonym** [comment]
Nice work, so if we want to run the longer tests so we just modify the TEMPEST_TESTS variable?  I can stamp out a few gate jobs to do periodic testing for us.

**Review by antonym — APPROVED** [review]

**Comment by coreywright** [comment]
@antonym,

yes, setting TEMPEST_TESTS, whether when running build.sh on the deploy host or overcloud-test.sh script manually on the director node, it allows setting what tempest tests to run (eg `--smoke`, `--regex ^tempest.scenario`, `--regex ^.*`).

WARNING: be careful with the test regex, eg `TEMPEST_TESTS=--regex .*` will not give the expected results due to unintentional shell glob expansion in `scripts/overcloud-test.sh`, but `TEMPEST_TESTS=--regex ^.*` works as intended:

```
# Run Tempest tests.
tempest run ${TEMPEST_OPTIONS} ${TEMPEST_TESTS} || RC=${?}
+ tempest run --concurrency 1 --regex . .. .stestr .stestr.conf
usage: tempest run [-h] [--workspace WORKSPACE]
                   [--workspace-path WORKSPACE_PATH]
                   [--config-file CONFIG_FILE] [--smoke | --regex REGEX]
                   [--black-regex BLACK_REGEX]
                   [--whitelist-file WHITELIST_FILE]
                   [--blacklist-file BLACKLIST_FILE] [--load-list LOAD_LIST]
                   [--list-tests] [--concurrency CONCURRENCY]
                   [--parallel | --serial] [--save-state] [--subunit]
                   [--combine]
tempest run: error: unrecognized arguments: .. .stestr .stestr.conf
+ RC=2
```

NOTE: the default behavior of tempest is to run all tests when no tests are specified, ie `TEMPEST_TESTS=""`, which should work when running `build.sh`, but not when manually running `scripts/overcloud-tests.sh` because of the way bash defaults work and instead the default or whatever was specified with `build.sh` is used (ie `TEMPEST_TESTS="${TEMPEST_TESTS:-<whatever build.sh set tempest_tests to>}"` treats TEMPEST_TESTS the same whether it's unset or `""` and always results in `<whatever build.sh set tempest_test to>`).

**Pull request merged**
