### PR TITLE
RI-464 Adds Ceph Support

### PR DESCRIPTION
**Pull request by antonym**
Builds and configures a basic Ceph Cluster by default.  Can be disabled with the ENABLE_CEPH_STORAGE flag during build.

### CODE REVIEW

**Comment by antonym** [comment]
recheck_all

**Comment by antonym** [comment]
Did a second pass of this manually on my dev node and the ceph cluster comes up healthy.  Going ahead and merging this to unblock testing.

**Comment by coreywright** [comment]
sorry i wasn't quick enough.

i tried testing this on my dev node this morning, it failed (for an unrelated reason) while i was working on something else (experimenting and documenting nested virt), and before i had a chance to get back to it and conduct testing, you just merged it.

**Comment by antonym** [comment]
No worries, just wanted to get another team unblocked, if you see anything off with it let me know.  Am going to try and do a pass on that tempest stuff today, but also was going to start getting swift working.

**Pull request merged**
